import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { ProjectType } from "./project-type.js";

/**
 * Generate docs/writekit.md — a complete user guide tailored to the project type.
 * Regenerated on every init/sync/build. The user should not edit this file.
 */
export async function generateDocs(projectDir: string, typeDef: ProjectType): Promise<void> {
    const docsDir = join(projectDir, "docs");
    await mkdir(docsDir, { recursive: true });
    await writeFile(join(docsDir, "writekit.md"), buildGuide(typeDef));
}

function buildGuide(t: ProjectType): string {
    const hasDir = (d: string) => t.dirs.includes(d);
    const hasFile = (f: string) => t.files.includes(f);
    const hasCmd = (c: string) => t.add_commands.includes(c);

    const sections: string[] = [];

    // Header
    sections.push(`# writekit — ${t.name} Guide

> Auto-generated by writekit. Do not edit — this file is refreshed on every build/sync.

## Quick start

\`\`\`bash
wk check          # validate project
wk build html     # build as web page
wk build epub     # build as ePub ebook
wk build pdf      # build as PDF
wk build docx     # build as Word document
wk build md       # build as single Markdown
wk build all      # build all formats
wk watch          # watch for changes, rebuild automatically
wk stats          # word count, reading time, chapter balance
\`\`\`
`);

    // Adding content
    const addCmds: string[] = [];
    if (hasCmd("chapter")) addCmds.push("wk add chapter <title>           # new chapter");
    if (hasCmd("chapter") && t.features.supports_parts) addCmds.push('wk add chapter <title> --part 1   # chapter inside part 1');
    if (hasCmd("part")) addCmds.push('wk add part <title>               # new part');
    if (hasCmd("character")) addCmds.push("wk add character <name>           # character sheet");
    if (hasCmd("location")) addCmds.push("wk add location <name>            # worldbuilding entry");
    if (hasCmd("concept")) addCmds.push("wk add concept <term>             # concept/term definition");
    if (hasCmd("argument")) addCmds.push("wk add argument <claim>           # argument sheet");
    if (hasCmd("note")) addCmds.push("wk add note <title>               # free-form note");
    if (hasCmd("event")) addCmds.push("wk add event <description>        # timeline event");
    if (hasCmd("source")) addCmds.push("wk add source <title>             # bibliography source");
    addCmds.push("wk add author <name>              # add an author");
    addCmds.push("wk add translator <name>          # add a translator");
    // Front/back matter
    if (hasCmd("dedication")) addCmds.push("wk add dedication                 # dedication page");
    if (hasCmd("epigraph")) addCmds.push("wk add epigraph                   # opening quotation(s)");
    if (hasCmd("preface")) addCmds.push("wk add preface                    # preface");
    if (hasCmd("foreword")) addCmds.push("wk add foreword                   # foreword");
    if (hasCmd("prologue")) addCmds.push("wk add prologue                   # prologue");
    if (hasCmd("epilogue")) addCmds.push("wk add epilogue                   # epilogue");
    if (hasCmd("afterword")) addCmds.push("wk add afterword                  # afterword");
    if (hasCmd("appendix")) addCmds.push("wk add appendix                   # appendix");
    if (hasCmd("author-note")) addCmds.push("wk add author-note               # author's note");

    sections.push(`## Adding content

\`\`\`bash
${addCmds.join("\n")}
\`\`\`
`);

    // Removing and renaming
    sections.push(`## Removing and renaming

\`\`\`bash
wk remove chapter <number>        # remove + renumber
${hasCmd("part") ? 'wk remove part <number>           # remove part (chapters move to root)\n' : ""}wk remove author <name>            # remove from project
${hasCmd("character") ? 'wk rename character <old> <new>   # rename everywhere\n' : ""}${hasCmd("location") ? 'wk rename location <old> <new>    # rename everywhere\n' : ""}${hasCmd("concept") ? 'wk rename concept <old> <new>     # rename everywhere\n' : ""}\`\`\`
`);

    // Import/Export
    sections.push(`## Import and export

\`\`\`bash
wk import <file.md>               # split markdown into chapters by # headings
wk import <file.md> --start-at 5  # start numbering at 5
wk export                         # dump entire project to single .md
wk export -o path.md              # export to specific file
\`\`\`
`);

    // Translation
    sections.push(`## Translation

\`\`\`bash
wk translate init --to en          # create translation project
wk translate init --to en --context # include context dirs (${hasDir("characters") ? "characters, " : ""}${hasDir("world") ? "world, " : ""}outline)
wk translate glossary              # show glossary progress
wk translate status                # translation progress per file
wk translate verify                # check glossary consistency
wk translate sync                  # sync with source changes
wk translate diff                  # show outdated files
\`\`\`

Translation projects live in \`translations/<lang>/\`. Each is a standalone writekit project.
`);

    // Configuration
    sections.push(`## Configuration

### config.yaml

\`\`\`yaml
title: "My ${t.name}"
author: "Your Name"
language: en
build_formats:
    - html
    - epub
theme: default
# print_preset: trade    # optional — enables print features
\`\`\`

### style.yaml

\`\`\`yaml
narrator: third-person     # first-person | third-person | omniscient | second-person
pov: ""                    # default POV character(s) — name or list of names
tense: past                # past | present
tone: ""
voice: ""
rules: []

# Text normalization (optional)
dialogue_style: em_dash    # em_dash | double_quotes | guillemets | angle_quotes
smart_quotes: true         # " → \\u201C\\u201D
normalize_ellipsis: true   # ... → \\u2026
normalize_dashes: true     # -- → \\u2014
\`\`\`

When normalization rules are set, \`wk check\` warns about violations and \`wk sync\` auto-fixes them.

### Narrator vs POV

These are two distinct concepts:

- **\`narrator\`** — the narrative voice type. Set in \`style.yaml\` as the project default, overridable per chapter.
  - \`first-person\`: the narrator is a character ("I walked...")
  - \`third-person\`: external narrator following one character's thoughts ("He walked... he thought...")
  - \`omniscient\`: external narrator who knows everything ("Meanwhile, across town, she was thinking...")
  - \`second-person\`: rare ("You walk into the room...")

- **\`pov\`** — the point-of-view character(s). Who the reader experiences the scene through. Can be a single name or a list.
  - In first-person: who is the "I"
  - In third-person: whose thoughts we follow
  - In omniscient: optional, indicates the focus character(s) of the scene

### Typography overrides

\`\`\`yaml
# In style.yaml — only include what you want to change
typography:
    paragraph_indent: "0"
    paragraph_spacing: 0.5rem
    text_align: left
    line_height: "2.0"
    scene_break: "* * *"
    chapter_opening: large         # large | medium | small
    chapter_heading: title         # title | label_number_title | label_number | number_title | number
    part_heading: label_number_title
\`\`\`
`);

    // Print presets
    sections.push(`## Print presets

By default, all projects use \`screen\` (A4, no print features). Add \`print_preset\` to enable print layout:

| Preset | Size | Features |
|---|---|---|
| \`screen\` | A4 | no print features (default) |
| \`a4\` | 210×297mm | page numbers |
| \`a5\` | 148×210mm | full print (numbers, headers, mirror margins, recto start) |
| \`trade\` | 6×9in | full print |
| \`kdp\` | 6×9in + bleed | full print (Amazon KDP) |
| \`ingramspark\` | 6×9in + bleed | full print |
| \`pocket\` | 4.25×7in | full print |
| \`digest\` | 5.5×8.5in | full print |
| \`royal\` | 6.14×9.21in | full print |
| \`lulu\` | 6×9in + bleed | full print |
`);

    // Themes and fonts
    sections.push(`## Themes and fonts

\`\`\`bash
wk theme list                  # available themes
wk theme use <name>            # switch theme
wk theme create <name>         # create custom theme
\`\`\`

**Fonts**: place \`.woff2\`, \`.ttf\`, or \`.otf\` files in \`assets/fonts/\` or \`themes/<name>/fonts/\`. They are auto-embedded in HTML (base64) and ePub (ZIP entries). Reference them in your theme CSS.

**DOCX templates**: place a \`template.docx\` in \`assets/\` to customize Word output styles and fonts.
`);

    // Markdown
    sections.push(`## Markdown reference

| Syntax | Result |
|---|---|
| \`# Heading\` | Chapter/section title |
| \`**bold**\` | **bold** |
| \`*italic*\` | *italic* |
| \`> quote\` | Blockquote |
| \`- item\` | Bullet list |
| \`1. item\` | Numbered list |
| \`[text](url)\` | Link |
| \`![alt](assets/img.jpg)\` | Image |
| \`![alt](assets/img.jpg){width=50%}\` | Image with width |
| \`text[^1]\` + \`[^1]: note\` | Footnote |
| \`---\` | Scene break / horizontal rule |
`);

    // Frontmatter
    sections.push(`## Frontmatter fields

### Manuscript chapters
| Field | Required | Description |
|---|---|---|
| \`title\` | yes | Chapter title |
${hasCmd("chapter") ? '| `chapter` | yes | Chapter number |\n' : ""}| \`narrator\` | no | Override narrative voice for this chapter (first-person, third-person, omniscient, second-person) |
| \`pov\` | no | Point-of-view character(s) — name or list of names |
| \`draft\` | no | Draft number (tracked in reports) |
${t.features.show_chapter_author ? '| `author` | no | Per-chapter author |\n' : ""}| \`show_title\` | no | Set to false to hide heading |
| \`toc\` | no | Set to false to exclude from TOC |
`);

    if (hasDir("characters")) {
        sections.push(`### Characters
| Field | Required |
|---|---|
| \`name\` | yes |
| \`role\` | yes (protagonist, antagonist, supporting, minor) |
| \`aliases\` | no |
| \`age\` | no |
| \`relationships\` | no |
`);
    }

    if (hasDir("world")) {
        sections.push(`### World / Locations
| Field | Required |
|---|---|
| \`name\` | yes |
| \`type\` | yes (location, culture, system, etc.) |
`);
    }

    if (hasDir("concepts")) {
        sections.push(`### Concepts
| Field | Required |
|---|---|
| \`term\` | yes |
| \`related\` | no |
`);
    }

    if (hasDir("arguments")) {
        sections.push(`### Arguments
| Field | Required |
|---|---|
| \`claim\` | yes |
| \`related\` | no |
`);
    }

    // Validation
    sections.push(`## Validation

\`wk check\` validates:
- Missing/malformed YAML files
- Frontmatter schema (required/optional fields per type)
- Cross-references (POV characters, relationships, locations, concepts)
- Draft tracking consistency
- Timeline chronological order
- Text normalization rules
- Naming conventions

Run \`wk check\` before every build.
`);

    // Supported languages
    sections.push(`## Supported languages

en, it, fr, de, es, pt, ru, ar, hi, zh, ko, ja, nl, pl, tr, sv, el

Set \`language\` in config.yaml. Controls editorial labels (Table of Contents, Colophon, etc.) and heading numerals.
`);

    return sections.join("\n");
}
